layout_spectrum: 0.6569651
typography_spectrum: 0.1893001
color:
  saturation: 0.4119425
  lightness: 0.7610164
  brandStrength: 0.01677697
  rhythmicContrast: 0.02793052
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Avec Cinta
